version: '3.7'
services:
  walnut-lang-php:
    depends_on:
     - mysql
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./code:/var/www/html
    ports:
     - "8002:80"
volumes:
  db_data:
